#!/usr/bin/env php

<?php

use Swoole\Coroutine;
use Symfony\Component\Console\Application;
use Xycc\Winter\Core\Commands\ServerCommand;

require __DIR__ . '/vendor/autoload.php';

Coroutine::set(['hook_flags' => SWOOLE_HOOK_ALL]);

$application = new \App\Application();

$application->start(__DIR__);

$command = new Application();
$command->add(new ServerCommand($application));
$command->setAutoExit(false);
return $command->run();